# Generated by Django 5.0 on 2023-12-30 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('auth_user', models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cuit', models.IntegerField(blank=True, null=True)),
                ('contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('acceso', models.CharField(blank=True, choices=[('', 'Seleccionar...'), ('expositores', 'Expositores'), ('tecnica', 'Técnica'), ('trabajadores', 'Trabajadores'), ('allAccess', 'All Access'), ('armado', 'Armado'), ('desarme', 'Desarme')], default='', max_length=20, null=True)),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.evento')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombreyapellido', models.CharField(max_length=200)),
                ('acceso', models.CharField(choices=[('', 'Seleccionar...'), ('expositores', 'Expositores'), ('tecnica', 'Técnica'), ('trabajadores', 'Trabajadores'), ('allAccess', 'All Access'), ('armado', 'Armado'), ('desarme', 'Desarme')], default='', max_length=20)),
                ('asistencia', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=200)),
                ('fechaHastaSeguro', models.DateField(null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.empresa')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.evento')),
            ],
            options={
                'unique_together': {('dni', 'evento')},
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('poliza', models.IntegerField(blank=True, null=True)),
                ('montos', models.BooleanField()),
                ('clausulas', models.BooleanField()),
                ('fechaDesde', models.DateField()),
                ('fechaHasta', models.DateField()),
                ('tomador', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.empresa')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.persona')),
            ],
        ),
    ]
