# Generated by Django 5.1.4 on 2024-12-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persona',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
    ]
